# Generated by Django 3.1.5 on 2021-01-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department'], 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name', 'second_name'], 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position'], 'verbose_name_plural': 'Должности'},
        ),
    ]
