# Generated by Django 3.1.5 on 2021-01-30 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210130_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(help_text='Введите отдел', on_delete=django.db.models.deletion.CASCADE, to='polls.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=200, validators=[django.core.validators.RegexValidator('^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$', 'Неверный формат номера телефона')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(help_text='Введите должность', on_delete=django.db.models.deletion.CASCADE, to='polls.position', verbose_name='Должность'),
        ),
    ]
